name: Label Pull Requests

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ready for Release to Production'
        required: true
        default: 'Production'
        type: choice
        options:
          - Re-run Action  

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add default label
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        label: "default-label"
