name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Production'
        required: true
        default: 'Production'
        type: choice
        options:
          - PRODUCTION
          - UAT
          - CAT
          - DEVELOPMENT

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       node-version: [22.2.0]

    steps:
     - name: Checkout repository
       uses: actions/setup-node@v3

     - name: Setup Node.js 22.x
       uses: actions/setup-node@v3
       with:
         node-version: '22.x'

     - name: Add Node.js to PATH
       run: echo "/home/runner/work/test-repo" >> $GITHUB_PATH    

     - name: Install dependencies
       run: npm install
       working-directory: /home/runner/work/test-repo

     - name: Run build
       run: npm run build
       working-directory: /home/runner/work/test-repo

     - name: Run tests
       run: npm test
       working-directory: /home/runner/work/test-repo
      
     - name: Set environment variables
       run: echo "NODE_ENV=production" >> $GITHUB_ENV

     - name: Display directory structure
       run: ls -la /home/runner/work/test-repo/*

     #- name: Set execute permissions on script
       #run: chmod 775 /home/runner/work/test-repo/.github/package.json

     #- name: Run a script
       #run:  ./package.json
       #working-directory: /home/runner/work/test-repo

    #- name: Set up Node.js 20.x
      #uses: actions/setup-node@v3
      #with:
        #node-version: '20.x'

    #- name: Install dependencies
      #run: npm install
      #working-directory: ./

     #- name: Run build
       #run: npm run build
       #working-directory: ./

     #- name: Run tests
       #run: npm test
       #working-directory: ./
