name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'Production'
        type: choice
        options:
          - Production
          - Development
          - CAT
          - UAT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
