name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'Production'
        type: choice
        options:
          - Production
          - Development
          - CAT
          - UAT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Deploying to ${{ github.event.inputs.environment }} environment"

    - name: Send email notification
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Build Failed - ${{ github.repository }}
        to: derick.williams1@nara.gov
        from: notifications@github.com
        body: |
          The build for ${{ github.repository }} has failed.
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Please check the logs for more details.

    - name: Send email notification
      if: ${{ success() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Build Succeeded - ${{ github.repository }}
        to: derick.williams1@nara.gov
        from: notifications@github.com
        body: |
          The build for ${{ github.repository }} has succeeded.
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Please check the logs for more details.     
